/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javanew;

public class App {
	
   public String getGreeting(){
	   return "hello";
   }
    public static void main(String[] args) {
        System.out.println("hello world");
    }
}
